## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [14]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [26]:
# 1) Seu código aqui
df_mat_per = df_mat/24
df_por_per = df_por/18
df_geo_per = df_por/8
df_ing_per = df_ing/8
df_his_per = df_his/8
df_fis_per = df_fis/12
df_qui_per = df_fis/12

In [27]:
# 2) Seu código aqui
df_acertos_total = df_mat+df_por+df_geo+df_ing+df_his+df_fis+df_qui
df_acertos_total.head()

   Qt_acertos
0          35
1          48
2          50
3          32
4          30

In [28]:
# 3) Seu código aqui
df_acertos_total_per = df_acertos_total/(24+18+8+8+8+12+12)
df_acertos_total_per.head()

   Qt_acertos
0    0.388889
1    0.533333
2    0.555556
3    0.355556
4    0.333333

In [41]:
# 4) Seu código aqui

df_acertos_total[df_acertos_total['Qt_acertos']>45].count()

Qt_acertos    31
dtype: int64

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [64]:
# seu código aqui
#1
df_alunos = pd.concat([df_mat, df_por, df_geo, df_ing, df_his, df_fis, df_qui], axis=1)
df_alunos.columns = ['acertos_mat', 'acertos_por', 'acertos_geo', 'acertos_ing', 'acertos_his', 'acertos_fis', 'acertos_qui']
df_alunos.head()

,acertos_mat,acertos_por,acertos_geo,acertos_ing,acertos_his,acertos_fis,acertos_qui
0,6,7,7,3,1,8,3
1,19,10,0,0,0,11,8
2,14,16,0,5,7,4,4
3,10,7,3,4,0,0,8
4,7,2,2,7,0,9,3

In [65]:
df_reprovados = df_alunos[(df_alunos['acertos_mat']==0)|(df_alunos['acertos_fis']==0)|(df_alunos['acertos_qui']==0)]
df_reprovados

,acertos_mat,acertos_por,acertos_geo,acertos_ing,acertos_his,acertos_fis,acertos_qui
3,10,7,3,4,0,0,8
6,6,0,7,7,5,0,4
10,10,8,3,2,1,7,0
12,20,8,3,7,1,0,3
14,7,11,1,7,1,4,0
20,23,11,6,5,6,2,0
25,0,4,7,4,0,4,8
26,11,14,6,2,7,0,0
27,21,13,1,5,7,3,0
33,14,8,0,5,6,6,0
35,11,14,6,3,3,0,11
49,8,1,1,0,1,0,8
56,7,6,7,5,6,0,8
65,1,8,2,4,3,0,6
66,5,4,3,6,3,0,10
72,11,16,3,4,7,0,9
73,1,16,2,4,3,0,11
74,9,11,0,7,5,7,0
84,15,1,0,5,1,0,4
89,23,11,7,7,6,9,0
92,14,10,1,6,1,8,0
94,0,5,2,6,1,3,8
98,0,10,3,1,5,10,11

In [66]:
#2
df_reprovados.shape[0]

23

In [67]:
#3
df_alunos[['acertos_his', 'acertos_geo']].mean()

acertos_his    3.60
acertos_geo    3.36
dtype: float64

In [68]:
#4
df_alunos['acertos_totais'] = df_alunos[:].sum(axis=1)
df_alunos

,acertos_mat,acertos_por,acertos_geo,acertos_ing,acertos_his,acertos_fis,acertos_qui,acertos_totais
0,6,7,7,3,1,8,3,35
1,19,10,0,0,0,11,8,48
2,14,16,0,5,7,4,4,50
3,10,7,3,4,0,0,8,32
4,7,2,2,7,0,9,3,30
...,...,...,...,...,...,...,...,...
95,6,4,7,1,4,9,3,34
96,8,1,4,6,1,4,3,27
97,23,5,0,2,4,1,5,40
98,0,10,3,1,5,10,11,40
99,11,15,0,1,6,7,2,42

In [70]:
df_aprovados = df_alunos[(df_alunos['acertos_totais']>=45)&(df_alunos['acertos_mat']!=0)&(df_alunos['acertos_fis']!=0)&(df_alunos['acertos_qui']!=0)]
df_aprovados

,acertos_mat,acertos_por,acertos_geo,acertos_ing,acertos_his,acertos_fis,acertos_qui,acertos_totais
1,19,10,0,0,0,11,8,48
2,14,16,0,5,7,4,4,50
5,20,2,5,3,2,9,9,50
7,18,4,4,7,7,1,8,49
8,22,9,2,7,6,5,7,58
17,21,15,2,2,4,2,6,52
18,20,4,3,5,3,11,4,50
24,20,2,7,5,3,11,2,50
31,15,13,3,1,3,9,10,54
34,18,14,1,0,6,3,3,45
36,22,9,6,6,1,4,8,56
37,19,12,5,7,1,6,2,52
39,4,16,2,4,6,9,8,49
40,18,3,6,3,6,5,6,47
42,20,6,7,7,2,3,3,48
45,17,10,0,2,6,9,4,48
48,17,6,0,7,5,9,11,55
53,14,11,3,4,3,7,3,45
60,16,8,0,4,4,7,9,48
62,17,6,2,4,7,1,9,46
67,21,0,7,2,4,2,10,46
70,21,14,0,3,5,11,8,62
71,17,8,7,6,4,2,9,53
77,15,2,5,7,6,11,7,53
78,14,16,7,2,7,11,9,66
80,13,16,5,1,7,2,1,45
81,22,16,2,0,4,1,10,55
88,20,1,1,5,7,9,7,50
93,12,16,5,5,6,6,6,56

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [74]:
arquivo = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-33f5906d-948d-406f-a178-4be5caaa6941.c000.csv'

In [79]:
# 1) Sua solução aqui
df = pd.read_csv(arquivo, sep=';')
df.head()

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,4e992b56-494a-43a6-b093-9f3450338bda-i0b0,07c37bf70113e321baba138c594fdc8558918fc9ae9ab3...,30,1991-06-08,F,4,AMARELA,120050.0,10.0,SENA MADUREIRA,...,2.0,Faixa Etária,1855836,JANSSEN,Organization/30587,2022-01-24,Reforço,88,COVID-19 JANSSEN - Ad26.COV2.S,Novo PNI
1,3967865c-b6fa-4a8d-a430-66951ce0b6a8-i0b0,99fc01166027e2f59e87c64891ee6c4a11f0ab331534d3...,39,1982-06-18,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,216VCD203Z,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-09-14,2ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
2,46789ecc-1396-44d9-9ffa-066f7c7b45b4-i0b0,3257f40e44ff74c885665f31c9414b9c8e6ca4d415055d...,42,1980-12-13,M,3,PARDA,150030.0,10.0,AFUA,...,2.0,Faixa Etária,213J21A,JANSSEN,30587,2022-12-16,2º Reforço,88,COVID-19 JANSSEN - Ad26.COV2.S,Novo PNI
3,39ea8a3e-c0fd-4ff2-832e-3407e8ec4f3a-i0b0,753775b512e58039c7143bb573afc053e94e2b2162d450...,35,1986-06-30,M,99,SEM INFORMACAO,120035.0,10.0,MARECHAL THAUMATURGO,...,2.0,Faixa Etária,210348,SINOVAC/BUTANTAN,Organization/61189445000156,2021-09-15,1ª Dose,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI
4,b0407d2b-2a79-4b41-9153-801907dab9e8-i0b0,e914b6fec9f4f3deef4772b84f5c289918012a032e42f8...,14,2007-02-22,M,1,BRANCA,120001.0,10.0,ACRELANDIA,...,2.0,Faixa Etária,FH4750,PFIZER,Organization/28290,2021-12-07,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI

In [80]:
df.shape[0]

387151

In [81]:
# 2) 
df['paciente_id'].nunique()

316503

In [90]:
# 3) 
df['paciente_id'].loc[df['vacina_descricao_dose']=='1ª Dose'].nunique()

143220

In [8]:
# 3) solução alternativa

In [91]:
# 4) 
df['paciente_id'].loc[df['paciente_idade']<18].nunique()

68247

In [93]:
# 5)
df.columns

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_dataNascimento', 'paciente_enumSexoBiologico',
       'paciente_racaCor_codigo', 'paciente_racaCor_valor',
       'paciente_endereco_coIbgeMunicipio', 'paciente_endereco_coPais',
       'paciente_endereco_nmMunicipio', 'paciente_endereco_nmPais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumNacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoAtendimento_codigo',
       'vacina_grupoAtendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataAplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem'],
      dtype='object')

In [94]:
df['estabelecimento_razaoSocial'].nunique()

62

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [95]:
# 1) 
df2 = df[df['paciente_idade']<18]
df2.head()

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
4,b0407d2b-2a79-4b41-9153-801907dab9e8-i0b0,e914b6fec9f4f3deef4772b84f5c289918012a032e42f8...,14,2007-02-22,M,1,BRANCA,120001.0,10.0,ACRELANDIA,...,2.0,Faixa Etária,FH4750,PFIZER,Organization/28290,2021-12-07,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
6,be81627d-bd64-46d1-8a06-db192f25b32d-i0b0,1c73fc1c8e107fb9b99e687cfcf916a4a0e51787073c3b...,13,2008-10-20,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,210390A,SINOVAC/BUTANTAN,152,2022-06-02,Reforço,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI
10,a4208578-d598-4d44-9eda-1cb0aa23775e-i0b0,28ca968328b60b50f5db16ea47cd2427e834afec771af8...,16,2005-01-28,F,99,SEM INFORMACAO,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FA9096,PFIZER,Organization/00394544000851,2021-08-06,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
19,3ab3ca95-392b-492c-97bb-39ae70cda1ef-i0b0,a18b9ad6266cb8b333a3c19bf3926cd01e66d032a6b259...,16,2005-06-21,F,3,PARDA,120042.0,10.0,RODRIGUES ALVES,...,2.0,Faixa Etária,FF8840,PFIZER,Organization/00394544000851,2021-09-29,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
25,3b0f4d79-97b8-4ed2-ae4d-b95cf6b60063-i0b0,689b07de5d0df4b9abdcaeeea64043926abe576b3d8dca...,12,2009-08-21,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,32010BD,PFIZER,Organization/28290,2021-12-13,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI

In [96]:
df2.shape[0]

77294

In [100]:
# 2) 
df2.columns

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_dataNascimento', 'paciente_enumSexoBiologico',
       'paciente_racaCor_codigo', 'paciente_racaCor_valor',
       'paciente_endereco_coIbgeMunicipio', 'paciente_endereco_coPais',
       'paciente_endereco_nmMunicipio', 'paciente_endereco_nmPais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumNacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoAtendimento_codigo',
       'vacina_grupoAtendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataAplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem'],
      dtype='object')

In [101]:
# 3)
df2['vacina_categoria_nome'].value_counts()

vacina_categoria_nome
Faixa Etária                                      47550
Povos Indígenas                                    4668
Outros                                             3755
Povos e Comunidades Tradicionais                    819
Trabalhadores de Saúde                              254
Comorbidades                                         56
População Privada de Liberdade                       53
Gestantes                                            42
Pessoas com Deficiência                              11
Pessoas Institucionalizadas                           3
Trabalhadores da Educação                             2
Pessoas de 60 anos ou mais institucionalizadas        1
Puérperas                                             1
Name: count, dtype: int64

In [104]:
# 4)
est_columns = ['estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf']
est_columns

['estabelecimento_valor',
 'estabelecimento_razaoSocial',
 'estalecimento_noFantasia',
 'estabelecimento_municipio_codigo',
 'estabelecimento_municipio_nome',
 'estabelecimento_uf']

In [105]:
# 5)
df_est = df2.loc[:, est_columns]

In [111]:
#6
df_est_list = df_est.drop_duplicates()
df_est_list

,estabelecimento_valor,estabelecimento_razaoSocial,estalecimento_noFantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
4,3006166,PREFEITURA MUNICIPAL DE ACRELANDIA,UNIDADE DE SAUDE DA FAMILIA NORTON VITORINO BOHEN,120001,ACRELANDIA,AC
6,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
19,2000016,PREFEITURA MUNICIPAL DE RODRIGUES ALVES,UNIDADE BASICA PADRE TEODORO ARNDS,120042,RODRIGUES ALVES,AC
27,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
29,2001217,PREFEITURA MUNICIPAL DE XAPURI,UNIDADE SAUDE DA FAMILIA JOSE FADUL,120070,XAPURI,AC
...,...,...,...,...,...,...
172202,197599,CENTRAL MUNICIPAL DE REDE DE FRIOS,CENTRAL MUNICIPAL DE REDE DE FRIOS,120020,CRUZEIRO DO SUL,AC
188768,5493455,PREFEITURA MUNICIPAL DE PLACIDO DE CASTRO,U S F MARIO GOMES DA SILVA,120038,PLACIDO DE CASTRO,AC
197308,2001357,SECRETARIA MUNICIPAL DE SAUDE DE BRASILEIA,ESF PEDRO OLIVEIRA DE SOUZA,120010,BRASILEIA,AC
305763,755605,USF BARRO VERMELHO,USF BARRO VERMELHO,120040,RIO BRANCO,AC
381901,7565089,PREFEITURA MUNICIPAL DE RIO BRANCO,USF MARIA DE JESUS III,120040,RIO BRANCO,AC